name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  dotenv: ^3.0.0
  mysql1: ^0.19.0
  shelf: ^1.3.0
  get_it: ^7.2.0
  logger: ^1.0.0
  injectable: ^1.5.4
  # shelf_router: ^1.1.0

dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.3.0
  injectable_generator: ^1.5.5
  # http: ^1.1.0
  # lints: ^3.0.0
  # test: ^1.24.0

dependency_overrides:
  # Overrides for the MySQL1 because the null safety is not applied yet
  logging: ^1.0.0
  crypto: ^3.0.0
